apiVersion: v1
kind: Service
metadata:
    name: "chilidogdev-09de"
    labels:
        app: "chilidogdev-09de"
spec:
    type: LoadBalancer
    ports:
    - port: 3003
      targetPort: 3003
      protocol: TCP
      name: http
    selector:
        app: "chilidogdev-09de"